### ISSUE TITLE
buggy install on openmm8 with python 3.9

### ISSUE THREAD

**Issue by blakemertz** [seekrcentral/openmm_ramd#1]
Really appreciate the effort in putting together this package to run RAMD in OpenMM. I've got a local install of OpenMM8, python 3.9 that I'm trying to get your package to successfully run. Following the installation instructions, openmm_ramd is installed, but it is clear that some of the calls (like with setuptools) are deprecated. I'm attaching my log file from the install.

When I go to run python setup.py test, I get the following error:

```
python setup.py test
/media/Data/binaries/miniconda3/envs/openmm/lib/python3.9/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
running pytest
running egg_info
writing openmm_ramd.egg-info/PKG-INFO
writing dependency_links to openmm_ramd.egg-info/dependency_links.txt
writing requirements to openmm_ramd.egg-info/requires.txt
writing top-level names to openmm_ramd.egg-info/top_level.txt
reading manifest file 'openmm_ramd.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CODE_OF_CONDUCT.md'
warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
adding license file 'LICENSE'
writing manifest file 'openmm_ramd.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "/media/Data/binaries/github/openmm_ramd/setup.py", line 21, in <module>
    setup(
  File "/media/Data/binaries/miniconda3/envs/openmm/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/media/Data/binaries/miniconda3/envs/openmm/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/media/Data/binaries/miniconda3/envs/openmm/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/media/Data/binaries/miniconda3/envs/openmm/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/media/Data/binaries/miniconda3/envs/openmm/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/media/Data/binaries/miniconda3/envs/openmm/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/media/Data/binaries/github/openmm_ramd/.eggs/pytest_runner-6.0.0-py3.9.egg/ptr/__init__.py", line 203, in run
    return self.run_tests()
  File "/media/Data/binaries/github/openmm_ramd/.eggs/pytest_runner-6.0.0-py3.9.egg/ptr/__init__.py", line 214, in run_tests
    result_code = __import__('pytest').main()
ModuleNotFoundError: No module named 'pytest'
```
which makes sense, based on my reading of the output from the install. In addition, when I go to run the test example, I get the following error:

```
python hsp90_ramd_example.py 
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Traceback (most recent call last):
  File "/media/Data/binaries/github/openmm_ramd/openmm_ramd/examples/hsp90_ramd_example.py", line 131, in <module>
    step_counter = simulation.run_RAMD_sim(
TypeError: run_RAMD_sim() got an unexpected keyword argument 'ramdSteps'
```
I know the code is probably not actively being developed, but if you could point me in the right direction to debug these issues, I'm happy to provide my modifications to the code to make it compatible with OpenMM8. Thanks!
[install.log](https://github.com/seekrcentral/openmm_ramd/files/11357440/install.log)

**Comment by lvotapka** [comment]
Thanks, those were bugs in the example script and in the setup script. I just pushed some fixes, so give it a try when you can.

**Comment by blakemertz** [comment]
Thanks for the quick turnaround -- really appreciate it! I got a little farther this time on the test, but it is still failing on the argument "ramdSteps":

```
============================================== test session starts ===============================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0
rootdir: /media/Data/binaries/github/openmm_ramd
plugins: anyio-3.6.2
collected 3 items                                                                                                

openmm_ramd/tests/test_force.py .                                                                          [ 33%]
openmm_ramd/tests/test_openmm_ramd.py .F                                                                   [100%]

==================================================== FAILURES ====================================================
____________________________________________ test_openmm_run_RAMD_sim ____________________________________________

tmp_path = PosixPath('/tmp/pytest-of-blakem/pytest-0/test_openmm_run_RAMD_sim0')

    def test_openmm_run_RAMD_sim(tmp_path):
        log_file_name = os.path.join(tmp_path, "ramd.log")
        simulation = make_openmm_ramd_simulation_object(log_file_name)
>       step_counter = simulation.run_RAMD_sim(
            max_num_steps=50, ramdSteps=10, rMinRamd=0.025, forceOutFreq=10,
            maxDist=12.0)
E       TypeError: run_RAMD_sim() got an unexpected keyword argument 'ramdSteps'

openmm_ramd/tests/test_openmm_ramd.py:81: TypeError
============================================ short test summary info =============================================
FAILED openmm_ramd/tests/test_openmm_ramd.py::test_openmm_run_RAMD_sim - TypeError: run_RAMD_sim() got an unexpected keyword argument 'ramdSteps'
========================================== 1 failed, 2 passed in 7.02s ===========================================
```
Is it sufficient to just delete the openmm_ramd directory for a fresh install, or are there other installation files that I need to track down before reinstalling and retesting?

**Comment by lvotapka** [comment]
Thanks, I just updated the test not to throw that error anymore. I've pushed the latest changes

**Comment by lvotapka** [comment]
And to answer your question, you shouldn't need to delete anything to reinstall. I think that just a "git pull origin master" followed by "python setup.py install" should be sufficient.

**Comment by blakemertz** [comment]
Thanks again. All the tests passed, but when I went to run the HSP90 example, I got a different error this time -- looks like it is pointing to an incorrect location for the CONDA installation:

```
python hsp90_ramd_example.py 
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Traceback (most recent call last):
  File "/media/Data/binaries/github/openmm_ramd/openmm_ramd/examples/hsp90_ramd_example.py", line 116, in <module>
    simulation = openmm_ramd.RAMDSimulation(
  File "/media/Data/binaries/miniconda3/envs/openmm/lib/python3.9/site-packages/openmm_ramd-0+unknown-py3.9.egg/openmm_ramd/openmm_ramd.py", line 93, in __init__
    super(RAMDSimulation, self).__init__(
  File "/media/Data/binaries/miniconda3/envs/openmm/lib/python3.9/site-packages/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/media/Data/binaries/miniconda3/envs/openmm/lib/python3.9/site-packages/openmm/openmm.py", line 10069, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: Error initializing CUDA: CUDA_ERROR_UNKNOWN (999) at /home/conda/feedstock_root/build_artifacts/openmm_1675115861220/work/platforms/cuda/src/CudaContext.cpp:140
```

**Comment by lvotapka** [comment]
I'm not sure what would cause that error. It looks to me like a problem with the OpenMM install. Have you tested your OpenMM installation to see whether the CUDA platform works?

```
python -m openmm.testInstallation
```
It's possible that OpenMM isn't correctly communicating with the NVIDIA driver. You might be able to try to install OpenMM with a different CUDA version, like the following:
```
conda install -c conda-forge openmm cudatoolkit=10.2
```
Also, it's possible that you have a GPU that is too old for the version of CUDA you are trying to use.

**Comment by blakemertz** [comment]
Good catch -- I'm running on my laptop in Linux, and having trouble specifying to OpenMM to choose the Nvidia card over the intel GPU:
```
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia python -m openmm.testInstallation

OpenMM Version: 8.0
Git Revision: a7800059645f4471f4b91c21e742fe5aa4513cda

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Error computing forces with CUDA platform

CUDA platform error: Error initializing CUDA: CUDA_ERROR_UNKNOWN (999) at /home/conda/feedstock_root/build_artifacts/openmm_1675115861220/work/platforms/cuda/src/CudaContext.cpp:140

Median difference in forces between platforms:

Reference vs. CPU: 6.29278e-06

All differences are within tolerance.
```
It's not an issue of updated drivers, old GPU (I have an RTX 3060), or cuda toolkit, as I'm running the 525.89 drivers and have cuda toolkit installed:
```
nvidia-smi
Mon May  1 10:36:40 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
| N/A   45C    P8    15W /  80W |     59MiB /  6144MiB |     11%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1062      G   /usr/lib/xorg/Xorg                 55MiB |
+-----------------------------------------------------------------------------+
```
My openmm environment:
```
conda list
# packages in environment at /media/Data/binaries/miniconda3/envs/openmm:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
amberlite                 22.0                     pypi_0    pypi
ambertools                22.3             py39h804d063_0    conda-forge
amberutils                21.0                     pypi_0    pypi
anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39hb9d737c_3    conda-forge
arpack                    3.7.0                hdefa2d7_2    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.0             pyha770c72_0    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.3               hafa529b_0    conda-forge
boost                     1.78.0           py39h7c9e3ff_4    conda-forge
boost-cpp                 1.78.0               h75c5d50_1    conda-forge
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
brotlipy                  0.7.0           py39hb9d737c_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2023.01.10           h06a4308_0  
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.3.0              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            ha61ee94_1014    conda-forge
certifi                   2022.12.7        py39h06a4308_0  
cffi                      1.15.1           py39he91dace_3    conda-forge
cftime                    1.6.2            py39h2ae25f5_1    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.3              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7            py39h4b4f3f3_0    conda-forge
cryptography              40.0.1           py39h079d5ae_0    conda-forge
cudatoolkit               11.8.0              h37601d7_11    conda-forge
cudnn                     8.4.1.50             hed8a83a_0    conda-forge
curl                      7.88.1               hdc1c0ab_1    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.33          py39h227be39_0    conda-forge
debugpy                   1.6.6            py39h227be39_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.1                    pypi_0    pypi
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h27087fc_0    conda-forge
fftw                      3.3.10          nompi_hf0379b8_106    conda-forge
flit-core                 3.8.0              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.39.2           py39h72bdee0_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
greenlet                  2.0.2            py39h227be39_0    conda-forge
hdf4                      4.2.15               h501b40f_6    conda-forge
hdf5                      1.14.0          nompi_hb72d44e_103    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.1.0              pyha770c72_0    conda-forge
importlib-resources       5.12.0             pyhd8ed1ab_0    conda-forge
importlib_metadata        6.1.0                hd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
iniconfig                 2.0.0                    pypi_0    pypi
ipykernel                 6.22.0             pyh210e3f2_0    conda-forge
ipython                   8.11.0             pyh41d4057_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.7.4              pyhd8ed1ab_0    conda-forge
jax                       0.3.25             pyhd8ed1ab_0    conda-forge
jaxlib                    0.3.25          cuda112py39h17d59b0_201    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter_client            8.1.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.0            py39hf3d152e_0    conda-forge
jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
jupyter_server            2.5.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.3              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py39hf939315_1    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20220623.0      cxx17_h05df665_6    conda-forge
libaec                    1.0.6                hcb278e6_1    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.88.1               hdc1c0ab_1    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libglib                   2.74.1               h606061b_1    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libgrpc                   1.51.1               h4fad500_1    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libllvm11                 11.1.0               he0ac6c6_5    conda-forge
libnetcdf                 4.9.1           nompi_hf3f8848_103    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libprotobuf               3.21.12              h3eb15da_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.5.0                ha587672_6    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.3.0                h0b41bf4_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.10.3               hca2bb57_4    conda-forge
libxslt                   1.1.37               h873f0b0_0    conda-forge
libzip                    1.9.2                hc929e4a_1    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvmlite                  0.39.1           py39h7d9a04d_1    conda-forge
lxml                      4.9.2            py39h14694de_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                2.1.2            py39h72bdee0_0    conda-forge
matplotlib-base           3.7.1            py39he190548_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mdtraj                    1.9.7            py39h62423bb_4    conda-forge
mistune                   2.0.5              pyhd8ed1ab_0    conda-forge
mmpbsa-py                 16.0                     pypi_0    pypi
mpiplus                   v0.0.1          pyhd8ed1ab_1004    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclassic                 0.5.3              pyhb4ecaf3_3    conda-forge
nbclient                  0.7.2              pyhd8ed1ab_0    conda-forge
nbconvert                 7.2.9              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.2.9              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.2.9              pyhd8ed1ab_0    conda-forge
nbformat                  5.8.0              pyhd8ed1ab_0    conda-forge
nccl                      2.14.3.1             h0800d71_0    conda-forge
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
netcdf-fortran            4.6.0           nompi_h6fc414f_104    conda-forge
netcdf4                   1.6.3           nompi_py39h9afb058_101    conda-forge
networkx                  3.0                pyhd8ed1ab_0    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
nose                      1.3.7                   py_1006    conda-forge
notebook                  6.5.3              pyha770c72_0    conda-forge
notebook-shim             0.2.2              pyhd8ed1ab_0    conda-forge
numba                     0.56.4           py39h61ddf18_0    conda-forge
numexpr                   2.8.3           py39hf625f34_101    conda-forge
numpy                     1.23.5           py39h3d75532_0    conda-forge
ocl-icd                   2.3.1                h7f98852_0    conda-forge
ocl-icd-system            1.0.0                         1    conda-forge
openff-amber-ff-ports     0.0.3              pyh6c4a22f_0    conda-forge
openff-forcefields        2023.02.1          pyh1a96a4e_0    conda-forge
openff-interchange        0.2.3              pyhd8ed1ab_1    conda-forge
openff-interchange-base   0.2.3              pyhd8ed1ab_1    conda-forge
openff-toolkit            0.12.1             pyhd8ed1ab_1    conda-forge
openff-toolkit-base       0.12.1             pyhd8ed1ab_1    conda-forge
openff-units              0.2.0              pyh1a96a4e_0    conda-forge
openff-utilities          0.1.8              pyh1a96a4e_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openmm                    8.0.0            py39hc5dd2c2_0    conda-forge
openmm-ramd               0+unknown                pypi_0    pypi
openmmforcefields         0.11.2             pyhd8ed1ab_1    conda-forge
openmmtools               0.21.4             pyhd8ed1ab_0    conda-forge
openssl                   3.1.0                h0b41bf4_0    conda-forge
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
packmol                   20.010               h86c2bf4_0    conda-forge
packmol-memgen            1.2.3rc0                 pypi_0    pypi
pandas                    1.5.3            py39h2ad29b5_0    conda-forge
pandoc                    3.1.1                h32600fe_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
panedr                    0.7.1              pyhd8ed1ab_0    conda-forge
parmed                    3.4.4            py39h227be39_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pbr                       5.11.1             pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
pdb4amber                 22.0                     pypi_0    pypi
pdbfixer                  1.8.1              pyh6c4a22f_0    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.4.0            py39h7207d5c_2    conda-forge
pint                      0.20.1             pyhd8ed1ab_0    conda-forge
pip                       23.0.1           py39h06a4308_0  
pixman                    0.40.0               h36c2ea0_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.2.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0                    pypi_0    pypi
pooch                     1.7.0              pyha770c72_3    conda-forge
prometheus_client         0.16.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
psutil                    5.9.4            py39hb9d737c_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycairo                   1.23.0           py39h23c5bb2_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.7           py39h72bdee0_0    conda-forge
pyedr                     0.7.1              pyhd8ed1ab_0    conda-forge
pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
pymbar                    4.0.1            py39h2ae25f5_1    conda-forge
pyopenssl                 23.1.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyrsistent                0.19.3           py39h72bdee0_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytables                  3.7.0            py39hf8baa48_4    conda-forge
pytest                    7.3.1                    pypi_0    pypi
python                    3.9.16          h2782a2a_0_cpython    conda-forge
python-constraint         1.4.0                      py_0    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.3             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      3_cp39    conda-forge
pytraj                    2.0.6                    pypi_0    pypi
pytz                      2023.2             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39hb9d737c_5    conda-forge
pyzmq                     25.0.2           py39h0be026e_0    conda-forge
rdkit                     2022.09.4        py39hb00a813_1    conda-forge
re2                       2023.02.01           hcb278e6_0    conda-forge
readline                  8.2                  h5eee18b_0  
reportlab                 3.6.12           py39h8bbe095_2    conda-forge
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
sander                    22.0                     pypi_0    pypi
scipy                     1.10.1           py39h7360e5f_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                65.6.3           py39h06a4308_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
smirnoff99frosst          1.1.0              pyh44b312d_0    conda-forge
snappy                    1.1.10               h9fff704_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlalchemy                2.0.7            py39h72bdee0_0    conda-forge
sqlite                    3.41.1               h5eee18b_0  
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
terminado                 0.17.1             pyh41d4057_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tinydb                    4.7.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1                    pypi_0    pypi
tornado                   6.2              py39hb9d737c_1    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2022g                h04d1e81_0  
unicodedata2              15.0.0           py39hb9d737c_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
validators                0.20.0             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.5.1              pyhd8ed1ab_0    conda-forge
wheel                     0.38.4           py39h06a4308_0  
widgetsnbextension        3.6.3              pyhd8ed1ab_0    conda-forge
xmltodict                 0.13.0             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.8.4                h0b41bf4_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.10               h5eee18b_1  
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
```
Isn't there a call to openMM to specify which device to choose when running openMM? I seem to recall there being one but can't find it in the documentation. I shouldn't need to specify my nvcc location, since openMM is already installed, so my next guess is to specify the CUDA device? http://docs.openmm.org/latest/userguide/library/04_platform_specifics.html Sorry, I know this is outside the scope of the current issue, but figured I'd ask.

**Comment by lvotapka** [comment]
Ah I see. You can try to modify the "cuda_index" variable in the script, to specify to use a different GPU:

```
cuda_index = "1"
```

**Comment by blakemertz** [comment]
Had to reboot my laptop -- apparently the CUDA pointers get messed up when you put your laptop to sleep and a reboot is the only way to solve the problem #https://github.com/openmm/openmm/issues/3638 

After reboot, the HSP90 example script and testinstallation scripts worked. 
```
recomputing force!
recomputing force!
recomputing force!
recomputing force!
recomputing force!
recomputing force!
#"Step","Potential Energy (kJ/mole)","Temperature (K)","Box Volume (nm^3)"
300000,-354810.7465753362,299.44856983961307,263.1234544992788
recomputing force!
recomputing force!
recomputing force!
```
Thanks again for the quick help, really appreciate it. I've been looking for RAMD implementations in other codes besides Gromacs and NAMD for quite some time now, and was really excited to come across your plugin for OpenMM. I'll close this issue, and if I have any questions on issues setting up my own RAMD runs, I'll open up a new issue request.

**Comment by lvotapka** [comment]
No problem, glad we got it working, and glad to have more users.
